### ISSUE TITLE
Consider continuous integration

### ISSUE THREAD

**Issue by exoego** [FujitsuLaboratories/escapin#1]
It looks like this repo has no continuous integration right now.
Could you consider setup CI at least for every pull requests?
CI ensures that changes passes tests and do not break build, so you can merge PRs with confidence, if properly configured.

My recommendation is [Travis CI](https://github.com/marketplace/travis-ci), since 
* its free plan for OSS have offers a lot: no limitation regarding build times, Linux/Windows environment, e.g..
  [Other CI providers](https://github.com/marketplace?category=continuous-integration&type=apps) may have a cap for free plan, like 1000 minutes per month limitation..
* its user community is vast, so contributors can improve CI configuration.

**Comment by kimusaku** [comment]
Thanks for your suggestion.
I am now using Travis CI for pull requests.
See #5.
